### ISSUE TITLE
License

### ISSUE THREAD

**Issue by guilhermetrovo** [amusarra/liferay-portal-sqlserverdb-support#3]
Hi, is the license GPL or LGPL?
Looking at the pom it has both, the name is GPL but the link is LGPL!

<name>GNU General Public License (GPLv2.1)</name>
<url>http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html</url>

**Comment by amusarra** [comment]
Hi.
Sorry, but the link is bad. The license is GPL

**Comment by guilhermetrovo** [comment]
Thanks for the prompt reply!
